### ISSUE TITLE
LastReads.h 

### ISSUE THREAD

**Issue by d4n4mp** [CalPlug/ADE9078-3PhaseWattmeter#2]
The ADE9078.h includes LastReads.h but it isn't on the project. May you provide this source?

**Comment by mohannad999** [comment]
I face the same problem how I can solve that

**Comment by DavidJayBrady** [comment]
Original author here, just got an email from your comment.

LastReads.h was a file I made which contained structs of all the data I ever needed to read in. Why this file is completely missing from the current repo is beyond me... Hopefully it has been removed because another developer found a better alternative or had a good reason, but given that it is still in ADE9078.h, I'm not sure.

I dug through the commit history to find the file for you, here it is: https://github.com/CalPlug/ADE9078-3PhaseWattmeter/commit/faf6569d1eec1a15efd5bdd58aaf43792a29acd5#diff-7fe85efa02ee1aa58ad11b180a370c6b72cfcf0d4ca0a5de7b47c907e8401493

Try re-adding the file and running it, judging by the commit history it looks like the code hasn't changed much and may just work.
